version: "3.7"

services:
  database:
    image: postgres:9
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
  
  backend:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    environment:
      PG_CONNECTION_STRING: postgres://postgres:postgres@database/postgres

volumes:
  db-data:
    driver: local